#ifndef RENDERER_VERTEX_ATTR_DEF_H
#define RENDERER_VERTEX_ATTR_DEF_H



// Types of Vertex Attributes
enum AttribType {
	VERTEX_COORD_ATTRIB,
	NORMAL_ATTRIB,
	TEXTURE_COORD_ATTRIB,
	TANGENT_ATTRIB,
	BITANGENT_ATTRIB,
	VERTEX_ATTRIB1,
	VERTEX_ATTRIB2,
	VERTEX_ATTRIB3,
	VERTEX_ATTRIB4
};


#endif // !RENDERER_VERTEX_ATTR_DEF_H